// Datos reales de Alea Las Palmas.
export const ALEA_DATA = {
  webapp: "https://alea-webapp.vercel.app",
  publicSite: "https://alealaspalmas.es/",
  address: "C. São Paulo, 55 · 35008 Las Palmas de G.C.",
  email: "alealaspalmas@gmail.com",
  instagram: "https://www.instagram.com/alealaspalmas",
  facebook: "https://www.facebook.com/share/1Cdvz1KnLF/",
  mapsUrl: "https://maps.app.goo.gl/p94LY5QWHNeaTaBN7",
  fee: { amount: 20, period: "mes", periodEN: "month", currency: "€" },
  hours: { es: "Abierto 24/7", en: "Open 24/7" },
  founded: 2020,

  logoUrl: "https://alealaspalmas.es/wp-content/uploads/2025/11/logo_final_sin_fondo.png",
  heroBg: "https://alealaspalmas.es/wp-content/uploads/2025/10/fondo-oscuro.png",
  charactersImg: "https://alealaspalmas.es/wp-content/uploads/2025/10/image-removebg-preview.png",
  wizardImg: "https://alealaspalmas.es/wp-content/uploads/2025/10/image-12-e1761825612963.jpg",

  stats: [
    { n: "24/7",  labelES: "Acceso para socios", labelEN: "Members access" },
    { n: "60+",   labelES: "Eventos al año",     labelEN: "Events per year" },
    { n: "350+",  labelES: "Juegos en ludoteca", labelEN: "Games in library" },
    { n: "20+",   labelES: "Tiendas aliadas",    labelEN: "Partner shops" },
  ],

  // EVENTOS PRÓXIMOS — reales, con cartelería de alealaspalmas.es
  upcoming: [
    {
      id: "bolt-action",
      titleES: "Torneo de Bolt Action",
      titleEN: "Bolt Action Tournament",
      tagES: "Wargame · Histórico",
      tagEN: "Wargame · Historical",
      dateES: "10 MAY 2026",
      dateEN: "10 MAY 2026",
      dateLongES: "Sábado 10 de mayo de 2026",
      dateLongEN: "Saturday, 10 May 2026",
      time: "10:00 – 20:00",
      playersES: "16 plazas",
      playersEN: "16 seats",
      priceES: "15 € socios · 20 € no socios",
      priceEN: "€15 members · €20 non-members",
      organizerES: "Comisión de Wargames",
      organizerEN: "Wargames committee",
      tone: "warm",
      blurbES: "Early Theater · Sábado completo de partidas con material cedido por el club. Cuatro rondas suizas, premios para los tres primeros.",
      blurbEN: "Early Theater · Full Saturday of games with club-provided material. Four Swiss rounds, prizes for top three.",
      fullES: [
        "Cuatro rondas suizas en formato Early Theater (1939–1941). Listas de 1000 puntos según el reglamento Bolt Action 3rd Edition.",
        "El club aporta mesas terrenadas, escenografía y árbitros. Los participantes traen sus ejércitos.",
        "Comida y bebida disponible durante toda la jornada en la barra del local. Premios para los tres primeros y un premio especial al ejército mejor pintado.",
      ],
      fullEN: [
        "Four Swiss rounds in Early Theater format (1939–1941). 1000-point lists per Bolt Action 3rd Edition.",
        "The club provides terrained tables, scenery and umpires. Bring your own army.",
        "Food and drinks available all day at the bar. Prizes for the top three plus a special award for best-painted army.",
      ],
      bulletsES: ["4 rondas suizas", "Listas de 1000 puntos", "Premios para top 3 + mejor pintado", "Material de mesa cedido por Alea"],
      bulletsEN: ["4 Swiss rounds", "1000-point lists", "Top-3 + best-painted prizes", "Table material provided by Alea"],
      img: "https://alealaspalmas.es/wp-content/uploads/2026/04/ChatGPT-Image-10-abr-2026-16_36_29.png",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-12/",
    },
    {
      id: "bolt-days",
      titleES: "BOLT-DAYS",
      titleEN: "BOLT-DAYS",
      tagES: "Liga semanal",
      tagEN: "Weekly league",
      dateES: "Cada viernes",
      dateEN: "Every Friday",
      dateLongES: "Todos los viernes del año",
      dateLongEN: "Every Friday, year-round",
      time: "18:00 – cierre",
      playersES: "Mesa abierta",
      playersEN: "Open table",
      priceES: "Gratis para socios",
      priceEN: "Free for members",
      organizerES: "Comunidad Bolt de Alea",
      organizerEN: "Alea Bolt community",
      tone: "amber",
      blurbES: "Cada viernes montamos mesas de Bolt Action con escenarios temáticos. Llega cuando puedas, juega hasta que cierren.",
      blurbEN: "Every Friday we set up Bolt Action tables with themed scenarios. Drop in any time, play till close.",
      fullES: [
        "El viernes es el día sagrado del Bolt en Alea. Montamos 4–6 mesas con escenarios rotativos: Stalingrado, Normandía, Pacífico, Norte de África.",
        "Pasan principiantes, veteranos y todo lo que hay entre medias. Si vienes sin ejército, te emparejamos con alguien que te preste fuerzas.",
        "No hace falta apuntarse, sólo asomar la cabeza. Cierra cuando los jugadores deciden — habitualmente pasada la medianoche.",
      ],
      fullEN: [
        "Friday is the sacred Bolt day at Alea. We set up 4–6 tables with rotating scenarios: Stalingrad, Normandy, Pacific, North Africa.",
        "Beginners, veterans and everything in between drop in. No army? We'll pair you with someone who'll loan you forces.",
        "No sign-up needed, just show up. The night ends when the players decide — usually past midnight.",
      ],
      bulletsES: ["Escenarios temáticos rotativos", "Sin inscripción previa", "Mesas y miniaturas disponibles", "Cerveza fría en la barra"],
      bulletsEN: ["Rotating themed scenarios", "No sign-up needed", "Tables & miniatures available", "Cold beer at the bar"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/LOGO-ALEA-BOLT.png",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-4/",
    },
    {
      id: "fenix",
      titleES: "Los Puños del Fénix Rubí",
      titleEN: "Ruby Phoenix Tournament",
      tagES: "Rol · Pathfinder 2e",
      tagEN: "TTRPG · Pathfinder 2e",
      dateES: "Todo 2026",
      dateEN: "All 2026",
      dateLongES: "Campaña anual 2026 · sesiones quincenales",
      dateLongEN: "Year-long campaign 2026 · bi-weekly sessions",
      time: "Viernes 19:00 – 23:00",
      timeEN: "Fri 19:00 – 23:00",
      playersES: "6 jugadores",
      playersEN: "6 players",
      priceES: "Incluido en la cuota de socio",
      priceEN: "Included in membership",
      organizerES: "Javi (GM)",
      organizerEN: "Javi (GM)",
      tone: "ruby",
      blurbES: "Javi vuelve a dirigir la campaña insignia: torneo marcial en Goka, intrigas en la Liga Inmortal, mecánicas crujientes.",
      blurbEN: "Javi runs the flagship campaign again: martial tournament in Goka, intrigue in the Immortal League, crunchy mechanics.",
      fullES: [
        "La campaña insignia del club vuelve por tercer año. Pathfinder 2e con personajes de nivel 11 a 20 en Tian Xia, en la ciudad-Estado de Goka.",
        "Estructura mixta: arenas de torneo con luchas tácticas crujientes alternándose con sesiones de intriga y exploración por la ciudad.",
        "Cinco plazas reservadas + una rotativa para socios nuevos que quieran probar el sistema. Mesa cerrada tras la sesión 3.",
      ],
      fullEN: [
        "The club's flagship campaign returns for its third year. Pathfinder 2e with level 11–20 characters in Tian Xia, in the city-state of Goka.",
        "Mixed structure: tournament arenas with crunchy tactical fights alternating with city-wide intrigue and exploration.",
        "Five reserved seats + one rotating seat for new members to try the system. Roster closes after session 3.",
      ],
      bulletsES: ["Pathfinder 2e nivel 11–20", "Sesiones quincenales", "5 plazas fijas + 1 rotativa", "Personaje y fichas listas en sesión 0"],
      bulletsEN: ["Pathfinder 2e levels 11–20", "Bi-weekly sessions", "5 fixed + 1 rotating seat", "Character & sheets ready at session 0"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/ruby-phoenix.jpg",
      link: "https://alealaspalmas.es/los-punos-del-fenix-rubi-en-2026/",
    },
    {
      id: "gastro",
      titleES: "Jornadas Gastro-Lúdicas",
      titleEN: "Gastro-Gaming Nights",
      tagES: "Cultural · Cooperativo",
      tagEN: "Cultural · Co-op",
      dateES: "Casi todos los viernes",
      dateEN: "Most Fridays",
      dateLongES: "La mayoría de viernes del mes",
      dateLongEN: "Most Fridays of the month",
      time: "20:30 – 00:00",
      playersES: "Para socios",
      playersEN: "Members only",
      priceES: "5 € (cubre los ingredientes)",
      priceEN: "€5 (covers ingredients)",
      organizerES: "Comisión Gastro",
      organizerEN: "Gastro committee",
      tone: "olive",
      blurbES: "Nos ponemos los delantales: cocinamos juntos y combinamos cena con cooperativos en mesa larga.",
      blurbEN: "Aprons on: we cook together and pair dinner with co-op games on the long table.",
      fullES: [
        "Cocinamos entre todos un menú temático (japonés, mexicano, isleño...) y luego sacamos cooperativos de mesa larga: Spirit Island, Pandemic Legacy, Aeon's End.",
        "Es una de las actividades más queridas del club: socios que llegan tarde encuentran sitio en la mesa, plato caliente y un meeple.",
        "Plazas limitadas a 14 para que quepamos todos en la mesa. Se abren inscripciones el lunes anterior.",
      ],
      fullEN: [
        "We cook a themed menu together (Japanese, Mexican, island...) and then pull out long-table co-ops: Spirit Island, Pandemic Legacy, Aeon's End.",
        "One of the club's most beloved activities: latecomers find a seat at the table, a hot plate and a meeple.",
        "Limited to 14 seats so we all fit around the table. Sign-ups open the Monday before.",
      ],
      bulletsES: ["Menú temático rotativo", "Cooperativos de mesa larga", "14 plazas máximo", "Veggie/celíaco siempre disponible"],
      bulletsEN: ["Rotating themed menu", "Long-table co-op games", "14 seats max", "Veggie/GF always available"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/2025-11-05-19_15_07-Vista-superior-del-banquete-con-mucha-comida-_-Foto-gratuita.png",
      link: "https://alealaspalmas.es/jornadas-gastro-ludicas-2025/",
    },
  ],

  // EVENTOS REALIZADOS — historial real
  past: [
    {
      id: "clocktower-may",
      titleES: "Blood on the Clocktower",
      titleEN: "Blood on the Clocktower",
      dateES: "8 MAY 2026",
      dateLongES: "Viernes 8 de mayo de 2026",
      blurbES: "De la mano de Osiris, una noche de deducción social con 18 plazas completas.",
      fullES: ["Osiris dirigió una noche memorable de Blood on the Clocktower con 18 plazas completas y reservas en espera. Mecánica social, deducción intensa y un Bardo legendario que acabó ganando la noche.", "Repetiremos en 2027."],
      bulletsES: ["18 plazas", "GM: Osiris", "Storyteller pack 2024"],
      img: "https://alealaspalmas.es/wp-content/uploads/2026/04/ChatGPT-Image-16-abr-2026-12_06_38.png",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-13/",
    },
    {
      id: "cascadia",
      titleES: "Torneo de Cascadia",
      dateES: "26 ABR 2026",
      dateLongES: "Domingo 26 de abril de 2026",
      blurbES: "Tres rondas tranquilas, una final preciosa. Ganó la mesa de Marta.",
      fullES: ["Tres rondas suizas + final a cuatro. 24 jugadores, ambiente familiar y tablones llenos de bichos.", "Premios donados por La Comarca Games y NOVAilusión."],
      bulletsES: ["24 participantes", "3 rondas + final", "Premios cedidos por colaboradores"],
      img: "https://alealaspalmas.es/wp-content/uploads/2026/04/Cascadia-1086x1536.jpeg",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-11/",
    },
    {
      id: "guindilla-bowl",
      titleES: "Guindilla Bowl",
      dateES: "25 ABR 2026",
      dateLongES: "Sábado 25 de abril de 2026",
      blurbES: "Blood Bowl en formato corto: 7 entrenadores, una jornada épica.",
      fullES: ["Torneo NAF de Blood Bowl en formato Sevens, organizado junto a Demon Cup. Jornada completa con cuatro rondas y premios para los tres primeros."],
      bulletsES: ["Formato Sevens", "NAF-rated", "Co-organizado con Demon Cup"],
      img: "https://alealaspalmas.es/wp-content/uploads/2026/03/Guindilla-Bowl.jpeg",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-10-2-2/",
    },
    {
      id: "clocktower-mar",
      titleES: "Blood on the Clocktower",
      dateES: "21 MAR 2026",
      dateLongES: "Sábado 21 de marzo de 2026",
      blurbES: "Segunda noche de Clocktower en 2026: storyteller invitado y guion personalizado.",
      fullES: ["La fiebre de Clocktower llegó pronto a 2026. Esta sesión la dirigió Adri con un guion personalizado para el local."],
      bulletsES: ["16 plazas", "Guion exclusivo", "Storyteller: Adri"],
      img: "https://alealaspalmas.es/wp-content/uploads/2026/03/clocktower.jpeg",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-10-2/",
    },
    {
      id: "sushi-go",
      titleES: "Torneo de Sushi-Go!",
      dateES: "8 MAR 2026",
      dateLongES: "Domingo 8 de marzo de 2026",
      blurbES: "Familiar, rápido, delicioso. Mesas de 4 + final con maki-roll.",
      fullES: ["Torneo familiar de Sushi-Go! con tres rondas, mesas de 4 y final a 6. Atrajo a muchas familias del barrio."],
      bulletsES: ["Familiar", "3 rondas + final", "Premios Lifer"],
      img: "https://alealaspalmas.es/wp-content/uploads/2026/03/sushi-go.jpeg",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-10/",
    },
    {
      id: "demon-cup",
      titleES: "Demon Cup",
      dateES: "6 MAR 2026",
      dateLongES: "Viernes 6 a domingo 8 de marzo de 2026",
      blurbES: "El clásico anual NAF en Gran Canaria. Casa llena.",
      fullES: ["El torneo más esperado del calendario blood-bowlero en Canarias. Tres días, 32 entrenadores y nivel altísimo. Co-organizado con Demon Cup."],
      bulletsES: ["NAF-rated", "32 entrenadores", "3 días"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/demon-cup.jpg",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-2/",
    },
    {
      id: "convivencia",
      titleES: "Convivencia Ludens-Alea",
      dateES: "23–25 ENE 2026",
      dateLongES: "23 al 25 de enero de 2026",
      blurbES: "Tres días con la asociación hermana Ludens. Casa rural, mesas las 24h.",
      fullES: ["Convivencia anual con la asociación Ludens en una casa rural del norte. Mesas montadas las 24 horas, comida común y mucha amistad."],
      bulletsES: ["Casa rural", "3 días", "Junto a Ludens"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/12/Convivencia-2026.jpeg",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-9/",
    },
    {
      id: "luces",
      titleES: "Encendido de Luces Navideñas",
      dateES: "5 DIC 2025",
      dateLongES: "Viernes 5 de diciembre de 2025",
      blurbES: "Decoramos el local entre todos. Música, vino caliente y el árbol del club.",
      fullES: ["La tarde-noche en la que el local se transforma: montaje del árbol, decoración temática y mesas espontáneas hasta tarde."],
      bulletsES: ["Tradición anual", "Vino caliente", "Mesas espontáneas"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/12/ChatGPT-Image-2-dic-2025-00_02_53.png",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-8/",
    },
    {
      id: "level-up-40k",
      titleES: "Torneo Navideño en Level Up",
      dateES: "27 DIC 2025",
      dateLongES: "Sábado 27 de diciembre de 2025",
      blurbES: "W40K en Level Up: torneo de cierre de año, 16 listas.",
      fullES: ["Co-organizado con Level Up, este torneo cerró el año warhammero con 16 listas y altísimo nivel de pintura."],
      bulletsES: ["Warhammer 40K", "16 listas", "Co-organizado con Level Up"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/cartel-torneo-w40k-lvl-up-1090x1536.jpg",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-7/",
    },
    {
      id: "torneo-sda",
      titleES: "Torneo del Señor de los Anillos",
      dateES: "7 DIC 2025",
      dateLongES: "Fin de semana del 6 al 8 de diciembre de 2025",
      blurbES: "VI Torneo Navideño SDA: tres días en el puente, 24 jugadores.",
      fullES: ["El sexto Torneo Navideño de SDA Strategy Battle Game: tres días, 24 jugadores y la Comarca llena de fans."],
      bulletsES: ["6ª edición", "SBG Middle-earth", "3 días"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/Torneo-Senor-de-los-Anillos-recortado.jpg",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-6/",
    },
    {
      id: "spearhead",
      titleES: "II Torneo Spearhead",
      dateES: "29 NOV 2025",
      dateLongES: "Sábado 29 de noviembre de 2025",
      blurbES: "Spearhead AoS junto a El Bastión del Sur. Mesas espectaculares.",
      fullES: ["Segunda edición del torneo Spearhead de Age of Sigmar, co-organizado con El Bastión del Sur. Mesas terrenadas a juego con los ejércitos."],
      bulletsES: ["AoS Spearhead", "Co-org. Bastión del Sur", "Mesas terrenadas"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/Cartel-Torneo-Spearhead-1220x1536.jpg",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-3/",
    },
    {
      id: "liga-40k",
      titleES: "Liga Warhammer 40K en Alea",
      dateES: "1 NOV 2025 — abierta",
      dateLongES: "Comenzó el 1 de noviembre de 2025",
      blurbES: "Liga rotativa con sistema de puntuación propio. 18 entrenadores.",
      fullES: ["Liga interna abierta para socios. Sistema de puntuación propio que premia la consistencia y el espíritu deportivo."],
      bulletsES: ["18 entrenadores", "Sistema de puntos propio", "Abierta a socios"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/logo-alea.40k.png",
      link: "https://alealaspalmas.es/copia-template-evento-nombre-colaborador-y-logo-en-imagen-destacada-7-9-5/",
    },
    {
      id: "halloween",
      titleES: "Jornadas de Rol Terroríficas",
      dateES: "31 OCT 2025",
      dateLongES: "Día de los Finados, 31 de octubre de 2025",
      blurbES: "Mesas de rol de terror simultáneas, decoración a juego.",
      fullES: ["Aprovechamos el Día de los Finados para montar 4 mesas paralelas de rol de terror: Call of Cthulhu, Vaesen, World of Darkness y una de partida one-shot improvisada."],
      bulletsES: ["4 mesas paralelas", "Sistemas variados", "Decoración inmersiva"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/10/cartel-hallowen-1086x1536.jpg",
      link: "https://alealaspalmas.es/jornadas-de-rol-terrorificas-2025/",
    },
    {
      id: "abomination",
      titleES: "Las Bóvedas de la Abominación",
      dateES: "29 SEP 2025",
      dateLongES: "Lanzamiento 29 de septiembre de 2025",
      blurbES: "Campaña de Pathfinder en Belkorra: ¡el alcalde ha muerto!",
      fullES: ["Campaña insignia de Pathfinder 2e, ambientada en la pequeña ciudad de Belkorra. Sesiones quincenales con dos mesas paralelas."],
      bulletsES: ["Pathfinder 2e", "Niveles 1–10", "2 mesas paralelas"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/abomination-vaults.jpg",
      link: "https://alealaspalmas.es/las-bovedas-de-la-abominacion/",
    },
    {
      id: "comic-can-25",
      titleES: "Nos vemos en la Comic-Can 2025",
      dateES: "8 NOV 2025",
      dateLongES: "Comic-Can, 8 y 9 de noviembre de 2025",
      blurbES: "Mostramos el club en el salón con mesas abiertas todo el día.",
      fullES: ["Stand en la Comic-Can con mesas demo de wargames, rol y juegos familiares. Captamos +20 socios nuevos."],
      bulletsES: ["Stand Alea", "Mesas demo abiertas", "+20 socios nuevos"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/Cartel-comic-can-2025.png",
      link: "https://alealaspalmas.es/nos-vemos-en-la-comic-can-2025/",
    },
    {
      id: "heat",
      titleES: "Torneo de Heat 2025",
      dateES: "22 DIC 2025",
      dateLongES: "Lunes 22 de diciembre de 2025",
      blurbES: "Pilotos, arranquen motores. Heat: Pedal to the Metal con 12 corredores.",
      fullES: ["Torneo de Heat con sistema de carreras consecutivas. Doce pilotos, tres pistas distintas y ambiente de fórmula de la Sierra."],
      bulletsES: ["12 pilotos", "3 pistas", "Sistema acumulativo"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/heat.png",
      link: "https://alealaspalmas.es/torneo-de-heat-2025/",
    },
    {
      id: "alisios",
      titleES: "Torneo W40K en Los Alisios",
      dateES: "15 JUN 2025",
      dateLongES: "Domingo 15 de junio de 2025",
      blurbES: "Primer Alea-Gaming Experience: W40K en CC Los Alisios.",
      fullES: ["Primer torneo de W40K llevado fuera del local, en el espacio Gaming Experience de Los Alisios. 14 listas y mucho público."],
      bulletsES: ["W40K", "14 listas", "Centro comercial Los Alisios"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/torneo-de-Alisios.png",
      link: "https://alealaspalmas.es/primer-torneo-w40k-alea-gaming-experience-en-los-alisios-2025/",
    },
    {
      id: "aniversario",
      titleES: "Gran Fiesta de Aniversario",
      dateES: "5 JUL 2025",
      dateLongES: "Sábado 5 de julio de 2025",
      blurbES: "Cinco años de Alea: tarta, mesas las 24 horas y socios fundadores en la barra.",
      fullES: ["Celebramos los cinco años del club con tarta, ronda de discursos cortos, mesas 24 horas y los socios fundadores reviviendo la primera partida del club."],
      bulletsES: ["5º aniversario", "Mesas 24h", "Socios fundadores"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/aniversario.png",
      link: "https://alealaspalmas.es/gran-fiesta-de-aniversario-2025/",
    },
    {
      id: "dune",
      titleES: "Torneo de Dune: Imperium",
      dateES: "24 AGO 2025",
      dateLongES: "Domingo 24 de agosto de 2025",
      blurbES: "Dune: Imperium con final a cuatro y mucho Arrakis en mesa.",
      fullES: ["Torneo de Dune: Imperium con tres rondas suizas y final a cuatro. Carteles personalizados y mucho ambiente especiero."],
      bulletsES: ["3 rondas + final", "Dune: Imperium", "Premios Comarca"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/dune-imperium.png",
      link: "https://alealaspalmas.es/torneo-de-dune-imperium-2024/",
    },
    {
      id: "belselch",
      titleES: "Curso de pintura con Belselch Medina",
      dateES: "28 DIC 2024",
      dateLongES: "Sábado 28 de diciembre de 2024",
      blurbES: "Master class de pintura de miniaturas con Belselch Medina.",
      fullES: ["Belselch Medina, referente de la pintura en Canarias, impartió un curso de un día completo en el local con plazas limitadas."],
      bulletsES: ["Master class", "8 plazas", "Pintura de miniaturas"],
      img: "https://alealaspalmas.es/wp-content/uploads/2025/11/belselch.png",
      link: "https://alealaspalmas.es/curso-de-pintura-con-belselch-medina-2024/",
    },
  ],

  // JUEGOS FAVORITOS DEL CLUB
  featuredGames: [
    { title: "Bolt Action", category: "Wargame", players: "2", time: "120m", weight: 3.2 },
    { title: "Pathfinder 2e", category: "Rol", players: "3–6", time: "∞", weight: 4.1 },
    { title: "Warhammer 40K", category: "Wargame", players: "2", time: "150m", weight: 4.4 },
    { title: "Blood on the Clocktower", category: "Deducción", players: "5–20", time: "180m", weight: 2.7 },
    { title: "Cascadia", category: "Familiar", players: "1–4", time: "45m", weight: 1.9 },
    { title: "Heat: Pedal to the Metal", category: "Carreras", players: "2–6", time: "60m", weight: 2.4 },
    { title: "Dune: Imperium", category: "Estrategia", players: "1–4", time: "90m", weight: 3.0 },
    { title: "Blood Bowl", category: "Deportes", players: "2", time: "90m", weight: 3.0 },
  ],

  values: [
    {
      key: "comunidad",
      titleES: "Comunidad",
      titleEN: "Community",
      bodyES: "Cuidar y acompañar. Empatía, escucha y confianza mutua entre quienes comparten mesa.",
      bodyEN: "Care and company. Empathy, listening and mutual trust around the table.",
      icon: "🎲",
    },
    {
      key: "participacion",
      titleES: "Participación",
      titleEN: "Participation",
      bodyES: "Formar parte de algo vivo: compartir ideas, tiempo y experiencias en cada partida.",
      bodyEN: "Being part of something alive: sharing ideas, time and experience every game.",
      icon: "♟",
    },
    {
      key: "diversidad",
      titleES: "Diversidad",
      titleEN: "Diversity",
      bodyES: "Cada persona aporta algo único. Convivimos con respeto y celebramos lo distinto.",
      bodyEN: "Each person brings something unique. We live together with respect and celebrate difference.",
      icon: "🏳️‍🌈",
    },
  ],

  collaborators: [
    { name: "Amantis Informática",       img: "https://alealaspalmas.es/wp-content/uploads/2025/10/amantisinformatica.png", url: "https://maps.app.goo.gl/KPiF4nxabjBYu8YA6", descES: "Tienda de informática: ordenadores a medida, portátiles, móviles, tablets y mucho más.", descEN: "Computer store: custom PCs, laptops, phones, tablets and more." },
    { name: "El Desván del Leprechaun",  img: "https://alealaspalmas.es/wp-content/uploads/2025/10/eldesvandelleprechaun.png", url: "https://maps.app.goo.gl/CM96Gnighr4YGMbC7", descES: "Videojuegos, anime, manga, series y películas míticas.", descEN: "Video games, anime, manga, classic TV and film." },
    { name: "Friki Bar",                  img: "https://alealaspalmas.es/wp-content/uploads/2026/03/FrikiBar.png", url: "https://maps.app.goo.gl/i8yYakbETaJWTx197", descES: "Bar-cafetería alternativa: videojuegos, juegos de mesa, rol, cómics y decoración 100 % única.", descEN: "Alternative café: video games, board games, RPGs, comics — fully themed." },
    { name: "El Bastión del Sur",         img: "https://alealaspalmas.es/wp-content/uploads/2025/10/elbationdelsur.png", url: "https://maps.app.goo.gl/VH1ugGjcKhaZpA8i8", descES: "Productos relacionados con videojuegos, anime, manga, series y películas míticas.", descEN: "Video games, anime, manga, TV and film merchandise." },
    { name: "La Galería Bellas Artes",   img: "https://alealaspalmas.es/wp-content/uploads/2025/10/lagaleriadebellasartes--300x103.png", url: "https://maps.app.goo.gl/FGjD5c5x6QsAHGif9", descES: "Bellas artes: materiales de arte, manualidades, modelismo y scrapbooking.", descEN: "Fine art store: art supplies, crafts, modelling and scrapbooking." },
    { name: "NOVAilusión",                img: "https://alealaspalmas.es/wp-content/uploads/2026/03/NovaIlusion.png", url: "https://maps.app.goo.gl/h1K93SkEPfcrdhg56", descES: "Juguetería y librería: juegos de mesa, madera, cuentos, manualidades y puericultura.", descEN: "Toys & books: board games, wooden toys, kids' books, crafts and parenting." },
    { name: "Jugueterías LIFER",          img: "https://alealaspalmas.es/wp-content/uploads/2026/03/lifer-white.png", url: "https://maps.app.goo.gl/j44Ls2e65vyUNXFEA", descES: "Empresa familiar canaria: red de jugueterías especializadas en juegos, didáctica y libros.", descEN: "Family-run Canarian chain: specialised toy stores, learning material and books." },
    { name: "Shintori II",                img: "https://alealaspalmas.es/wp-content/uploads/2026/03/Shintori-1024x375.png", url: "https://maps.app.goo.gl/Jz6EF2jeWv4GSqpg9", descES: "Restaurante buffet a la carta: cocina china y japonesa.", descEN: "All-you-can-eat à-la-carte: Chinese & Japanese cuisine." },
    { name: "TCGuti",                     img: "https://alealaspalmas.es/wp-content/uploads/2026/03/TCGUTI-1-1.png", url: "https://maps.app.goo.gl/wKXMW3RBdXvd55eJ8", descES: "Coleccionismo: Funko Pops, juegos de mesa, Magic, Pokémon, Yu-Gi-Oh!, Lorcana y más.", descEN: "Collectibles: Funko Pops, board games, Magic, Pokémon, Yu-Gi-Oh!, Lorcana and more." },
    { name: "Juguetería Peluso",          img: "https://alealaspalmas.es/wp-content/uploads/2026/03/Peluso.png", url: "https://maps.app.goo.gl/bPhyoUJFbeDs4pht8", descES: "Una idea cocinada a fuego lento: jugar y fascinar al público más exquisito, los niños.", descEN: "Slow-cooked toy shop with one goal: delighting the most demanding crowd — kids." },
    { name: "Comic y Mazmorras",          img: "https://alealaspalmas.es/wp-content/uploads/2025/11/comicy-mazmorras.png", url: "https://maps.app.goo.gl/GMHQg1wfJ5aB1NfP6", descES: "Cómics, juegos de mesa, miniaturas y merchandise.", descEN: "Comics, board games, miniatures and merchandise." },
    { name: "Ludens",                     img: "https://alealaspalmas.es/wp-content/uploads/2025/10/asociacionlundens.png", url: "https://www.instagram.com/asoludens/", descES: "Asociación para la divulgación de los juegos de mesa como herramienta socioeducativa.", descEN: "Non-profit promoting board games as a socio-educational tool." },
    { name: "Samurai Cat Studio",         img: "https://alealaspalmas.es/wp-content/uploads/2025/10/samuraicat.png", url: "https://www.instagram.com/samuraicatstudio/", descES: "Taller de impresión 3D y tienda de coleccionables de rol, videojuegos y fantasía.", descEN: "3D-print workshop & store for RPG, video game and fantasy collectibles." },
    { name: "Level Up",                   img: "https://alealaspalmas.es/wp-content/uploads/2025/10/levelup.png", url: "https://maps.app.goo.gl/v5GzQPrSfDoqMWGd8", descES: "Juegos de mesa, cartas, miniaturas y rol. Ven a probarlos y disfrutarlos.", descEN: "Board games, card games, miniatures and TTRPGs. Come and try them." },
    { name: "La Comarca Games",           img: "https://alealaspalmas.es/wp-content/uploads/2025/10/lacomarca.png", url: "https://maps.app.goo.gl/Kpw7utWtqKY1bqbp7", descES: "Juegos de tablero, cartas, rol y wargames en Las Palmas de Gran Canaria.", descEN: "Board games, card games, RPGs and wargames in Las Palmas." },
    { name: "La Gruta del Goblin",        img: "https://alealaspalmas.es/wp-content/uploads/2025/10/lagrutadelgoblin-.png", url: "https://maps.app.goo.gl/yxy89D1hHWpoXg6a6", descES: "Cómics, manga, libros, merchandising, juegos de mesa, wargames, pinturas, Magic, etc.", descEN: "Comics, manga, books, merch, board games, wargames, paints, Magic, etc." },
    { name: "La Fortaleza",               img: "https://alealaspalmas.es/wp-content/uploads/2025/10/lafortaleza-.png", url: "https://maps.app.goo.gl/kv2DdkJARASkubWK8", descES: "Ordenadores, juegos, cartas, merchandising, wargames y centro de juegos.", descEN: "Computers, games, cards, merch, wargames and play centre." },
    { name: "La Forja 3D Lab",            img: "https://alealaspalmas.es/wp-content/uploads/2025/11/LaForja.png", url: "https://maps.app.goo.gl/PM5RftUDW5GGLRRT6", descES: "Miniaturas, escenarios y accesorios 3D para rol y juegos de cartas.", descEN: "3D miniatures, scenery and accessories for RPGs and card games." },
    { name: "El Trastero Mágico",         img: "https://alealaspalmas.es/wp-content/uploads/2025/10/eltrasteromagico.png", url: "https://maps.app.goo.gl/xWWxKpNM38oNSiX4A", descES: "Juegos de mesa, Warhammer, merchandising, Magic y organización de partidas.", descEN: "Board games, Warhammer, merch, Magic and event hosting." },
    { name: "Demon Cup",                  img: "https://alealaspalmas.es/wp-content/uploads/2025/11/LOGO-DEMON-CUP.jpg", url: "https://x.com/DemonCupBB?s=20", descES: "Impulsa el Blood Bowl en Gran Canaria: torneos NAF, ligas y eventos durante todo el año.", descEN: "Driving Blood Bowl in Gran Canaria: NAF tournaments, leagues and events year-round." },
  ],
};

// Diccionario i18n.
export const ALEA_I18N = {
  es: {
    "nav.about": "Sobre nosotros",
    "nav.events": "Eventos",
    "nav.culture": "Cultura",
    "nav.partners": "Colaboradores",
    "nav.contact": "Contacto",

    "cta.join": "Hazte socio",
    "cta.members": "Entrar al club",
    "cta.discover": "Ver eventos",
    "cta.calendar": "Calendario completo",

    "hero.tagline": "Asociación Cultural y Social",
    "hero.location": "Las Palmas de Gran Canaria",
    "hero.title.a": "Tira",
    "hero.title.b": "juega",
    "hero.title.c": "repite.",
    "hero.subtitle": "Apasionados de los juegos de rol, los juegos de mesa, los wargames y las miniaturas. Un local 24/7 para socios, una ludoteca abierta y 60+ eventos al año.",
    "hero.badge.open": "Abierto 24/7",
    "hero.badge.fee": "20 €/mes · socio",

    "events.kicker": "Próximos eventos",
    "events.title": "Lo que se cuece en Alea",
    "events.cta": "Apuntarme",
    "events.all": "Calendario completo",

    "cal.title": "Calendario Alea",
    "cal.subtitle": "Todo lo que viene y todo lo que ya pasó, mes a mes.",
    "cal.prev": "Mes anterior",
    "cal.next": "Siguiente mes",
    "cal.today": "Hoy",
    "cal.empty": "Sin eventos este día",
    "cal.emptyMonth": "No hay eventos programados este mes.",
    "cal.recurring": "Recurrente",
    "cal.upcoming": "Próximo",
    "cal.past": "Realizado",
    "cal.legend": "Leyenda",

    "past.kicker": "Eventos realizados",
    "past.title": "Lo que dejamos en el tapete",
    "past.subtitle": "Una selección de partidas, torneos y jornadas de los últimos meses.",

    "about.kicker": "Sobre Alea",
    "about.title": "Un club, no un comercio.",
    "about.body": "Somos una asociación sin ánimo de lucro de Las Palmas de Gran Canaria. Si te apasiona la fantasía, la estrategia o simplemente pasar un buen rato en buena compañía, este es tu sitio.",
    "about.body2": "Organizamos eventos que promueven la creatividad, el pensamiento estratégico y la socialización. Creemos en el poder del juego para conectar personas, romper barreras y construir comunidad.",
    "about.bullet.1": "Local en C. São Paulo, 55 (Schamann) abierto 24/7 para socios.",
    "about.bullet.2": "Ludoteca con más de 350 juegos en préstamo.",
    "about.bullet.3": "Maestros de juego veteranos para iniciar a quien venga nuevo.",
    "about.bullet.4": "Convenios con 20+ tiendas y bares de la isla.",

    "games.kicker": "Ludoteca",
    "games.title": "Lo que más rueda esta temporada",
    "games.subtitle": "Pasa el ratón sobre cualquier ficha. Cada caja es una invitación a una mesa.",

    "culture.kicker": "Nuestra cultura",
    "culture.title": "Tres tiradas que nunca fallamos",

    "partners.kicker": "Colaboradores",
    "partners.title": "Tiendas y aliados que hacen posible el club",

    "footer.find": "Encuéntranos",
    "footer.write": "Escríbenos",
    "footer.follow": "Síguenos",
    "footer.rights": "© 2026 Alea Las Palmas · Asociación sin ánimo de lucro",

    "easter.hint": "Pssst… anda un meeple suelto por aquí. Pillalo.",
    "egg.title": "¡Has tirado un 20 natural!",
    "egg.body": "Acabas de descubrir el easter egg. Mándale captura a la junta y te invitamos al primer café.",
    "egg.close": "Cerrar",

    "register.title": "Hazte socio de Alea",
    "register.body": "20 €/mes. Acceso al local 24/7, ludoteca completa, todos los eventos incluidos y descuentos en tiendas colaboradoras.",
    "register.benefit.1": "Acceso 24/7 con llave digital",
    "register.benefit.2": "Préstamo ilimitado de la ludoteca",
    "register.benefit.3": "Inscripción gratuita a todos los eventos",
    "register.benefit.4": "Descuentos en 20+ tiendas aliadas",

    "roll.cta": "Tira por mí",
    "roll.help": "Pulsa el dado y te asignamos un evento al azar",
    "roll.you": "Te toca",

    "modal.when": "Cuándo",
    "modal.where": "Dónde",
    "modal.who": "Plazas",
    "modal.price": "Precio",
    "modal.organizer": "Organiza",
    "modal.what": "En qué consiste",
    "modal.bullets": "Lo esencial",
    "modal.share": "Compartir",
    "modal.signup": "Apuntarme",
    "modal.directions": "Cómo llegar",
    "modal.close": "Cerrar",
  },
  en: {
    "nav.about": "About",
    "nav.events": "Events",
    "nav.culture": "Culture",
    "nav.partners": "Partners",
    "nav.contact": "Contact",

    "cta.join": "Become a member",
    "cta.members": "Member area",
    "cta.discover": "See events",
    "cta.calendar": "Full calendar",

    "hero.tagline": "Cultural & Social Association",
    "hero.location": "Las Palmas de Gran Canaria",
    "hero.title.a": "Roll",
    "hero.title.b": "play",
    "hero.title.c": "repeat.",
    "hero.subtitle": "Lovers of role-playing, board games, wargames and miniatures. A 24/7 members venue, an open library and 60+ events a year.",
    "hero.badge.open": "Open 24/7",
    "hero.badge.fee": "€20/month · member",

    "events.kicker": "Upcoming events",
    "events.title": "What's brewing at Alea",
    "events.cta": "Sign me up",
    "events.all": "Full calendar",

    "cal.title": "Alea calendar",
    "cal.subtitle": "Everything coming up and everything past, month by month.",
    "cal.prev": "Previous month",
    "cal.next": "Next month",
    "cal.today": "Today",
    "cal.empty": "No events on this day",
    "cal.emptyMonth": "No events scheduled this month.",
    "cal.recurring": "Recurring",
    "cal.upcoming": "Upcoming",
    "cal.past": "Past",
    "cal.legend": "Legend",

    "past.kicker": "Past events",
    "past.title": "What we've left on the table",
    "past.subtitle": "A pick of games, tournaments and meet-ups from the last few months.",

    "about.kicker": "About Alea",
    "about.title": "A club, not a shop.",
    "about.body": "We're a non-profit cultural association in Las Palmas de Gran Canaria. If you love fantasy, strategy or just spending a good evening in good company, this is your place.",
    "about.body2": "We run events that nurture creativity, strategic thinking and connection. We believe in the power of play to bring people together, break barriers and build community.",
    "about.bullet.1": "Venue at C. São Paulo, 55 (Schamann) open 24/7 for members.",
    "about.bullet.2": "Library of 350+ games to borrow.",
    "about.bullet.3": "Veteran game masters to onboard newcomers.",
    "about.bullet.4": "Partnerships with 20+ local shops and bars.",

    "games.kicker": "Game library",
    "games.title": "What's rolling most this season",
    "games.subtitle": "Hover any tile. Each box is an invitation to a table.",

    "culture.kicker": "Our culture",
    "culture.title": "Three rolls we never fumble",

    "partners.kicker": "Partners",
    "partners.title": "Shops and allies that keep the club running",

    "footer.find": "Find us",
    "footer.write": "Write us",
    "footer.follow": "Follow us",
    "footer.rights": "© 2026 Alea Las Palmas · Non-profit association",

    "easter.hint": "Psst… there's a stray meeple loose around here. Catch it.",
    "egg.title": "Natural 20!",
    "egg.body": "You found the easter egg. Screenshot it to the board and your first coffee's on us.",
    "egg.close": "Close",

    "register.title": "Become an Alea member",
    "register.body": "€20/month. 24/7 venue access, full library, all events included and discounts at partner shops.",
    "register.benefit.1": "24/7 access with digital key",
    "register.benefit.2": "Unlimited library lending",
    "register.benefit.3": "Free entry to every event",
    "register.benefit.4": "Discounts at 20+ partner shops",

    "roll.cta": "Roll for me",
    "roll.help": "Tap the die and we'll pick an event for you",
    "roll.you": "You get",

    "modal.when": "When",
    "modal.where": "Where",
    "modal.who": "Seats",
    "modal.price": "Price",
    "modal.organizer": "Organized by",
    "modal.what": "What it's about",
    "modal.bullets": "The essentials",
    "modal.share": "Share",
    "modal.signup": "Sign me up",
    "modal.directions": "Get directions",
    "modal.close": "Close",
  },
};
